name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2 instance
      run: |
        echo "Copying files to EC2 instance..."
        scp -r -o StrictHostKeyChecking=no main.py ${{ secrets.USERNAME }}@${{ secrets.EC2_INSTANCE_IP }}:/home/${{ secrets.USERNAME }}/my_project/ || exit 1

    - name: SSH into EC2 and run deployment script
      run: |
        echo "Connecting to EC2 instance and running deployment script..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.EC2_INSTANCE_IP }} 'bash -s' < ./deploy.sh || exit 1
