name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2 instance
      run: |
        scp -r -o StrictHostKeyChecking=no ./path/to/your/files ${{ secrets.USERNAME }}@<EC2_INSTANCE_IP>:/path/to/deploy/

    - name: SSH into EC2 and run deployment script
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@<EC2_INSTANCE_IP> 'bash -s' < ./path/to/your/deployment_script.sh
