name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      USERNAME: ec2-user  # Change to the correct user for your instance

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug EC2 Instance IP
      run: echo "EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}"

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no email_validator.py ${USERNAME}@${{ secrets.EC2_INSTANCE_IP }}:/home/ec2-user/
