# .github/workflows/deploy-to-ec2.yml

name: Deploy to EC2

on:
  push:
    branches:
      - main  # Run the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH to connect to the EC2 instance
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Store your private SSH key in GitHub Secrets

      # Step 3: Deploy the Python script to the EC2 instance
      - name: Copy script to EC2
        run: |
          scp -o StrictHostKeyChecking=no email_validator.py ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      # Step 4: Run the script on the EC2 instance
      - name: Execute script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "python3 /home/ec2-user/email_validator.py"
