name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Copy files to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem email_validator.py ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2 via SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} "cd /home/ubuntu && git pull origin main && source venv/bin/activate && pip install -r requirements.txt && sudo systemctl restart myapp.service"
